---
apiVersion: v1
kind: Pod
metadata:
 name: httpd-pod
 namespace: new-namespace
 labels:
  type: proxy
  author: webserver
spec:
  containers:
   - name: webserver
     image: httpd
     ports:
      - containerPort: 80
        hostPort: 7070
... 
