---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
   type: ci-cd
   author: jenkins
spec:
 containers:
  - name: jenkins-container
    image: jenkins/jenkins
    ports:
     - containerPort: 8080
       hostPort: 8080  
     
