---
apiVersion: v1
kind: Pod
metadata:
 name: postgres-pod
 labels:
  type: proxy1
spec:
 containers:
  - name: postgres-container
    image: postgres
    env:
     - name: POSTGRES_PASSWORD
       value: admin
     - name: POSTGRES_USER
       value: myuser
     - name: POSTGRES_DB
       value: mydb

